# This is a basic workflow to help you get started with Actions

name: Secret Sync

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Secrets Sync Action
      uses: jpoehnelt/secrets-sync-action@v1.7.1
      with:
        github_token: ${{ secrets.RSG_SYNC_TOKEN }}
        repositories: |
          RocketSurgeonsGuild/\w.*
        secrets: |
           RSG_PACKAGES_TOKEN
        # dry_run: true
      env:
         RSG_PACKAGES_TOKEN: ${{ secrets.RSG_PACKAGES_TOKEN }}
